// Auto-generated by AbhiBase AI App Generator
// Travel Booking App

export interface Destination {
  id: string
  name: string
  country: string
  description?: string
  image_url?: string
  price_from?: number
  created_at: string
  updated_at: string
}

export interface Trip {
  id: string
  destination_id: string
  start_date: string
  end_date: string
  budget?: number
  status: string
  created_at: string
  updated_at: string
}

export interface Booking {
  id: string
  trip_id: string
  type: string
  provider?: string
  confirmation?: string
  cost: number
  created_at: string
  updated_at: string
}

