// Auto-generated by AbhiBase AI App Generator
// Food Delivery App

export interface Restaurant {
  id: string
  name: string
  cuisine?: string
  rating?: number
  delivery_time?: string
  image_url?: string
  address: string
  created_at: string
  updated_at: string
}

export interface MenuItem {
  id: string
  name: string
  description?: string
  price: number
  category?: string
  image_url?: string
  restaurant_id: string
  created_at: string
  updated_at: string
}

export interface Order {
  id: string
  status: string
  total: number
  delivery_address: string
  user_id: string
  restaurant_id: string
  created_at: string
  updated_at: string
}

export interface OrderItem {
  id: string
  order_id: string
  menu_item_id: string
  quantity: number
  price: number
  created_at: string
  updated_at: string
}

export interface Delivery {
  id: string
  order_id: string
  driver_name?: string
  status: string
  estimated_arrival?: string
  created_at: string
  updated_at: string
}

