'use client';

import { useState } from 'react';
import { api } from '@/lib/api';

interface BrandData {
  brand: string;
  industry: string;
  values: string;
  style: string;
  colors: string;
  tagline: string;
  targetAudience: string;
}

interface BrandResult {
  concepts: { name: string; description: string; colors: string[]; font: string; symbols: string[] }[];
  colorPalette: { name: string; hex: string }[];
  typography: { heading: string; body: string }[];
  guidelines: string[];
}

export default function AdvancedLogoGenerator() {
  const [brand, setBrand] = useState<BrandData>({
    brand: '',
    industry: '',
    values: '',
    style: 'Modern',
    colors: '',
    tagline: '',
    targetAudience: '',
  });

  const [result, setResult] = useState<BrandResult | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedConcept, setSelectedConcept] = useState(0);
  const [activeTab, setActiveTab] = useState<'config' | 'preview' | 'code'>('config');

  const generateBrand = async () => {
    if (!brand.brand || !brand.industry) {
      alert('Please enter Brand Name and Industry');
      return;
    }

    setIsGenerating(true);
    try {
      const prompt = `Create a complete brand identity for "${brand.brand}" in the ${brand.industry} industry.

${brand.values ? `Values: ${brand.values}` : ''}
Style: ${brand.style}
${brand.colors ? `Preferred Colors: ${brand.colors}` : ''}
${brand.tagline ? `Tagline: ${brand.tagline}` : ''}
${brand.targetAudience ? `Target Audience: ${brand.targetAudience}` : ''}

Create 3 logo concepts and brand guidelines. Return JSON:
{
  "concepts": [
    {
      "name": "Concept Name",
      "description": "Description of the concept",
      "colors": ["#hex1", "#hex2"],
      "font": "Font recommendation",
      "symbols": ["symbol 1", "symbol 2"]
    }
  ],
  "colorPalette": [
    {"name": "Primary", "hex": "#xxxxxx"},
    {"name": "Secondary", "hex": "#xxxxxx"},
    {"name": "Accent", "hex": "#xxxxxx"},
    {"name": "Background", "hex": "#xxxxxx"}
  ],
  "typography": [
    {"heading": "Font Name", "body": "Font Name"}
  ],
  "guidelines": [
    "Guideline 1",
    "Guideline 2"
  ]
}`;

      const response = await api.ai.chat({
        messages: [{ role: 'user', content: prompt }],
        system: 'You are a brand strategist and designer. Create detailed, professional brand identity guidelines with color psychology and typography recommendations.'
      });

      const parsed = JSON.parse(response.response);
      setResult(parsed);
      setActiveTab('preview');
    } catch (error) {
      console.error('Failed to generate:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const generateLogoSvg = (concept: any, index: number): string => {
    const colors = concept.colors || ['#6366f1', '#8b5cf6'];
    const initials = brand.brand.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase();

    const shapes = [
      `<circle cx="50" cy="50" r="45" fill="${colors[0]}" opacity="0.1"/><circle cx="50" cy="50" r="35" fill="${colors[0]}"/><text x="50" y="58" text-anchor="middle" fill="white" font-size="24" font-weight="bold" font-family="Arial">${initials}</text>`,
      `<rect x="10" y="10" width="80" height="80" rx="16" fill="${colors[0]}" opacity="0.1"/><rect x="18" y="18" width="64" height="64" rx="12" fill="${colors[0]}"/><text x="50" y="58" text-anchor="middle" fill="white" font-size="24" font-weight="bold" font-family="Arial">${initials}</text>`,
      `<polygon points="50,5 95,27.5 95,72.5 50,95 5,72.5 5,27.5" fill="${colors[0]}" opacity="0.1"/><polygon points="50,15 85,32.5 85,67.5 50,85 15,67.5 15,32.5" fill="${colors[0]}"/><text x="50" y="58" text-anchor="middle" fill="white" font-size="22" font-weight="bold" font-family="Arial">${initials}</text>`,
    ];

    return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">${shapes[index % shapes.length]}</svg>`)}`;
  };

  const downloadBrandKit = () => {
    if (!result) return;

    const content = `# ${brand.brand} Brand Guidelines

## Logo Concepts
${result.concepts.map((c, i) => `
### ${c.name}
${c.description}
- Colors: ${c.colors.join(', ')}
- Font: ${c.font}
- Symbols: ${c.symbols.join(', ')}
`).join('')}

## Color Palette
${result.colorPalette.map(c => `- ${c.name}: ${c.hex}`).join('\n')}

## Typography
${result.typography.map(t => `- Heading: ${t.heading}\n- Body: ${t.body}`).join('\n')}

## Brand Guidelines
${result.guidelines.map((g, i) => `${i + 1}. ${g}`).join('\n')}

---
Generated by AbhiBase Logo Generator
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${brand.brand.toLowerCase().replace(/\s+/g, '-')}-brand-guidelines.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Advanced Logo & Brand Generator</h2>
          <p className="text-zinc-400">Create complete brand identities with logo concepts and guidelines</p>
        </div>
        <div className="flex gap-2">
          {['config', 'preview', 'code'].map(tab => (
            <button key={tab} onClick={() => setActiveTab(tab as any)} className={`px-4 py-2 rounded-lg capitalize ${activeTab === tab ? 'bg-violet-600' : 'bg-zinc-700'}`}>
              {tab === 'config' ? '⚙️ Config' : tab === 'preview' ? '🎨 Preview' : '📋 Guidelines'}
            </button>
          ))}
        </div>
      </div>

      {activeTab === 'config' ? (
        <div className="max-w-2xl mx-auto">
          <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
            <h3 className="font-semibold mb-4">🎨 Brand Configuration</h3>
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-zinc-400 mb-1">Brand Name *</label>
                  <input type="text" value={brand.brand} onChange={(e) => setBrand(prev => ({ ...prev, brand: e.target.value }))} placeholder="Your Brand" className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2" />
                </div>
                <div>
                  <label className="block text-sm text-zinc-400 mb-1">Industry *</label>
                  <input type="text" value={brand.industry} onChange={(e) => setBrand(prev => ({ ...prev, industry: e.target.value }))} placeholder="Technology, Fashion..." className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2" />
                </div>
              </div>
              <div>
                <label className="block text-sm text-zinc-400 mb-1">Brand Values</label>
                <input type="text" value={brand.values} onChange={(e) => setBrand(prev => ({ ...prev, values: e.target.value }))} placeholder="Innovation, Trust, Quality..." className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2" />
              </div>
              <div>
                <label className="block text-sm text-zinc-400 mb-1">Tagline</label>
                <input type="text" value={brand.tagline} onChange={(e) => setBrand(prev => ({ ...prev, tagline: e.target.value }))} placeholder="Innovating the future" className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-zinc-400 mb-1">Style</label>
                  <select value={brand.style} onChange={(e) => setBrand(prev => ({ ...prev, style: e.target.value }))} className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2">
                    {['Modern', 'Classic', 'Playful', 'Luxury', 'Minimal', 'Bold'].map(s => <option key={s} value={s}>{s}</option>)}
                  </select>
                </div>
                <div>
                  <label className="block text-sm text-zinc-400 mb-1">Preferred Colors</label>
                  <input type="text" value={brand.colors} onChange={(e) => setBrand(prev => ({ ...prev, colors: e.target.value }))} placeholder="Blue, White..." className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2" />
                </div>
              </div>
              <div>
                <label className="block text-sm text-zinc-400 mb-1">Target Audience</label>
                <input type="text" value={brand.targetAudience} onChange={(e) => setBrand(prev => ({ ...prev, targetAudience: e.target.value }))} placeholder="Young professionals, families..." className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-4 py-2" />
              </div>
              <button onClick={generateBrand} disabled={isGenerating} className="w-full bg-violet-600 hover:bg-violet-700 disabled:bg-zinc-700 py-3 rounded-lg font-medium">
                {isGenerating ? '⏳ Generating Brand Identity...' : '✨ Generate Brand Identity'}
              </button>
            </div>
          </div>
        </div>
      ) : activeTab === 'preview' ? (
        <div className="space-y-6">
          {result ? (
            <>
              {/* Logo Concepts */}
              <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
                <h3 className="font-semibold mb-4">🎯 Logo Concepts</h3>
                <div className="grid md:grid-cols-3 gap-4">
                  {result.concepts.map((concept, i) => (
                    <button
                      key={i}
                      onClick={() => setSelectedConcept(i)}
                      className={`bg-zinc-800/50 rounded-xl p-6 text-left border-2 transition-all ${
                        selectedConcept === i ? 'border-violet-500' : 'border-transparent hover:border-zinc-600'
                      }`}
                    >
                      <div className="flex justify-center mb-4">
                        <img src={generateLogoSvg(concept, i)} alt={concept.name} className="w-24 h-24" />
                      </div>
                      <h4 className="font-semibold text-center mb-2">{concept.name}</h4>
                      <p className="text-xs text-zinc-400 text-center">{concept.description}</p>
                      <div className="flex justify-center gap-1 mt-3">
                        {concept.colors.map((color, ci) => (
                          <div key={ci} className="w-5 h-5 rounded-full" style={{ backgroundColor: color }} />
                        ))}
                      </div>
                    </button>
                  ))}
                </div>
              </div>

              {/* Color Palette */}
              <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
                <h3 className="font-semibold mb-4">🎨 Color Palette</h3>
                <div className="grid grid-cols-4 gap-4">
                  {result.colorPalette.map((color, i) => (
                    <div key={i} className="text-center">
                      <div className="w-full h-20 rounded-lg mb-2" style={{ backgroundColor: color.hex }} />
                      <p className="font-medium text-sm">{color.name}</p>
                      <p className="text-xs text-zinc-400">{color.hex}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Typography */}
              <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
                <h3 className="font-semibold mb-4">🔤 Typography</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  {result.typography.map((t, i) => (
                    <div key={i} className="bg-zinc-800/50 rounded-lg p-4">
                      <p className="text-xs text-zinc-400 mb-1">Heading Font</p>
                      <p className="text-xl font-bold mb-3">{t.heading}</p>
                      <p className="text-xs text-zinc-400 mb-1">Body Font</p>
                      <p className="text-lg">{t.body}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Brand Preview */}
              <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
                <h3 className="font-semibold mb-4">👁️ Brand Preview</h3>
                <div className="bg-white rounded-xl overflow-hidden">
                  <div className="p-8 text-center" style={{ backgroundColor: result.colorPalette[0]?.hex || '#6366f1' }}>
                    <img src={generateLogoSvg(result.concepts[selectedConcept], selectedConcept)} alt="Logo" className="w-20 h-20 mx-auto mb-4" />
                    <h2 className="text-3xl font-bold text-white">{brand.brand}</h2>
                    {brand.tagline && <p className="text-white/80 mt-2">{brand.tagline}</p>}
                  </div>
                  <div className="p-8">
                    <h3 className="text-xl font-bold mb-4" style={{ color: result.colorPalette[0]?.hex }}>About Us</h3>
                    <p className="text-gray-600 mb-4">
                      We are {brand.brand}, a {brand.style.toLowerCase()} brand in the {brand.industry} industry.
                      {brand.values && ` Our values include ${brand.values.toLowerCase()}.`}
                    </p>
                    <div className="flex gap-4">
                      <button className="px-6 py-2 text-white rounded-lg" style={{ backgroundColor: result.colorPalette[0]?.hex }}>Learn More</button>
                      <button className="px-6 py-2 border-2 rounded-lg" style={{ borderColor: result.colorPalette[0]?.hex, color: result.colorPalette[0]?.hex }}>Contact Us</button>
                    </div>
                  </div>
                </div>
              </div>
            </>
          ) : (
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-8 text-center">
              <p className="text-6xl mb-4">🎨</p>
              <p className="text-zinc-400">Configure your brand and click Generate to see the preview</p>
            </div>
          )}
        </div>
      ) : (
        /* Guidelines */
        <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold">📋 Brand Guidelines</h3>
            <button onClick={downloadBrandKit} className="px-3 py-1 bg-violet-600 hover:bg-violet-700 rounded text-sm">💾 Download Guidelines</button>
          </div>
          {result ? (
            <div className="space-y-6">
              <div>
                <h4 className="font-semibold mb-2">Logo Concepts</h4>
                {result.concepts.map((c, i) => (
                  <div key={i} className="flex items-start gap-4 mb-4 bg-zinc-800/50 rounded-lg p-4">
                    <img src={generateLogoSvg(c, i)} alt={c.name} className="w-16 h-16" />
                    <div>
                      <p className="font-semibold">{c.name}</p>
                      <p className="text-sm text-zinc-400">{c.description}</p>
                      <p className="text-xs text-zinc-500 mt-1">Font: {c.font}</p>
                    </div>
                  </div>
                ))}
              </div>
              <div>
                <h4 className="font-semibold mb-2">Color Palette</h4>
                <div className="flex gap-3">
                  {result.colorPalette.map((c, i) => (
                    <div key={i} className="text-center">
                      <div className="w-12 h-12 rounded" style={{ backgroundColor: c.hex }} />
                      <p className="text-xs mt-1">{c.hex}</p>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-2">Guidelines</h4>
                <ol className="list-decimal list-inside space-y-1 text-sm text-zinc-400">
                  {result.guidelines.map((g, i) => <li key={i}>{g}</li>)}
                </ol>
              </div>
            </div>
          ) : (
            <p className="text-zinc-400 text-center">Generate a brand first to see guidelines</p>
          )}
        </div>
      )}
    </div>
  );
}
