'use client'

const RESTAURANTS = [
  { id: '1', name: 'Pizza Palace', cuisine: 'Italian', rating: 4.5, delivery_time: '30 min', address: '123 Main St' },
  { id: '2', name: 'Sushi Supreme', cuisine: 'Japanese', rating: 4.8, delivery_time: '25 min', address: '456 Oak Ave' },
  { id: '3', name: 'Burger Barn', cuisine: 'American', rating: 4.2, delivery_time: '20 min', address: '789 Elm St' },
  { id: '4', name: 'Taco Town', cuisine: 'Mexican', rating: 4.6, delivery_time: '35 min', address: '321 Pine Rd' },
  { id: '5', name: 'Curry Corner', cuisine: 'Indian', rating: 4.7, delivery_time: '40 min', address: '654 Maple Dr' },
]

const MENU_ITEMS = [
  { id: '1', name: 'Margherita Pizza', description: 'Fresh tomato, mozzarella, basil', price: 12.99, category: 'Pizza', restaurant: 'Pizza Palace' },
  { id: '2', name: 'Pepperoni Pizza', description: 'Classic pepperoni with cheese', price: 14.99, category: 'Pizza', restaurant: 'Pizza Palace' },
  { id: '3', name: 'Salmon Roll', description: 'Fresh salmon with rice', price: 8.99, category: 'Sushi', restaurant: 'Sushi Supreme' },
  { id: '4', name: 'Dragon Roll', description: 'Shrimp tempura with avocado', price: 12.99, category: 'Sushi', restaurant: 'Sushi Supreme' },
  { id: '5', name: 'Classic Burger', description: 'Beef patty with lettuce and tomato', price: 9.99, category: 'Burgers', restaurant: 'Burger Barn' },
  { id: '6', name: 'Cheeseburger', description: 'Double cheese with pickles', price: 11.99, category: 'Burgers', restaurant: 'Burger Barn' },
  { id: '7', name: 'Chicken Tacos', description: 'Grilled chicken with salsa', price: 7.99, category: 'Tacos', restaurant: 'Taco Town' },
  { id: '8', name: 'Beef Burrito', description: 'Loaded burrito with beans', price: 9.99, category: 'Burritos', restaurant: 'Taco Town' },
  { id: '9', name: 'Butter Chicken', description: 'Creamy tomato curry', price: 13.99, category: 'Curry', restaurant: 'Curry Corner' },
  { id: '10', name: 'Palak Paneer', description: 'Spinach with cheese cubes', price: 11.99, category: 'Curry', restaurant: 'Curry Corner' },
]

const ORDERS = [
  { id: '1', status: 'delivered', total: 27.98, address: '123 Home St', restaurant: 'Pizza Palace', date: '2026-09-14' },
  { id: '2', status: 'in_transit', total: 14.99, address: '456 Work Ave', restaurant: 'Sushi Supreme', date: '2026-09-15' },
]

export default function FoodDeliveryDemo() {
  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center py-6">
        <div className="inline-flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/20 rounded-full px-4 py-1.5 text-sm text-emerald-400 mb-4">
          🤖 Generated by AI App Generator
        </div>
        <h1 className="text-4xl font-bold mb-2">🍔 Food Delivery App</h1>
        <p className="text-zinc-400">Browse restaurants and order your favorite food</p>
        <div className="mt-3 text-xs text-zinc-600">
          Location: <code className="bg-zinc-800 px-2 py-1 rounded">generated-apps/food-delivery-app</code>
        </div>
      </div>
      
      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 text-center">
          <span className="text-2xl">🍕</span>
          <div className="text-2xl font-bold text-emerald-400 mt-1">{RESTAURANTS.length}</div>
          <div className="text-xs text-zinc-500">Restaurants</div>
        </div>
        <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 text-center">
          <span className="text-2xl">📋</span>
          <div className="text-2xl font-bold text-blue-400 mt-1">{MENU_ITEMS.length}</div>
          <div className="text-xs text-zinc-500">Menu Items</div>
        </div>
        <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 text-center">
          <span className="text-2xl">📦</span>
          <div className="text-2xl font-bold text-amber-400 mt-1">{ORDERS.length}</div>
          <div className="text-xs text-zinc-500">Orders</div>
        </div>
        <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 text-center">
          <span className="text-2xl">🧩</span>
          <div className="text-2xl font-bold text-violet-400 mt-1">8</div>
          <div className="text-xs text-zinc-500">Components</div>
        </div>
      </div>

      {/* Restaurants */}
      <section>
        <h2 className="text-xl font-bold mb-4">📍 Restaurants Near You</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {RESTAURANTS.map(r => (
            <div key={r.id} className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 hover:border-zinc-700 transition-all hover:scale-[1.02]">
              <div className="flex items-start justify-between mb-2">
                <h3 className="font-bold text-lg">{r.name}</h3>
                <span className="bg-emerald-500/20 text-emerald-400 px-2 py-0.5 rounded-full text-xs">⭐ {r.rating}</span>
              </div>
              <p className="text-sm text-zinc-400">{r.cuisine}</p>
              <div className="flex items-center justify-between mt-3 text-xs text-zinc-500">
                <span>📍 {r.address}</span>
                <span>🚚 {r.delivery_time}</span>
              </div>
            </div>
          ))}
        </div>
      </section>
      
      {/* Menu Items */}
      <section>
        <h2 className="text-xl font-bold mb-4">🍽️ Popular Items</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {MENU_ITEMS.map(item => (
            <div key={item.id} className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 hover:border-zinc-700 transition-all">
              <div className="flex items-start justify-between mb-2">
                <h3 className="font-bold">{item.name}</h3>
                <span className="text-emerald-400 font-bold">${item.price}</span>
              </div>
              <p className="text-sm text-zinc-400 mb-2">{item.description}</p>
              <div className="flex items-center justify-between text-xs">
                <span className="bg-zinc-800 text-zinc-300 px-2 py-0.5 rounded">{item.category}</span>
                <span className="text-zinc-500">from {item.restaurant}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Orders */}
      <section>
        <h2 className="text-xl font-bold mb-4">📦 Recent Orders</h2>
        <div className="space-y-3">
          {ORDERS.map(order => (
            <div key={order.id} className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-4 flex items-center gap-4">
              <div className={`w-3 h-3 rounded-full ${order.status === 'delivered' ? 'bg-emerald-500' : 'bg-amber-500 animate-pulse'}`} />
              <div className="flex-1">
                <div className="flex items-center gap-2">
                  <span className="font-bold">Order #{order.id}</span>
                  <span className={`text-xs px-2 py-0.5 rounded-full ${order.status === 'delivered' ? 'bg-emerald-500/20 text-emerald-400' : 'bg-amber-500/20 text-amber-400'}`}>
                    {order.status === 'delivered' ? '✓ Delivered' : '🚚 In Transit'}
                  </span>
                </div>
                <p className="text-sm text-zinc-400">{order.restaurant} • {order.address}</p>
              </div>
              <div className="text-right">
                <div className="font-bold text-lg">${order.total}</div>
                <div className="text-xs text-zinc-500">{order.date}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Files Generated */}
      <section className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-6">
        <h2 className="text-xl font-bold mb-4">📁 Generated Files</h2>
        <div className="grid md:grid-cols-2 gap-4">
          <div>
            <h3 className="text-sm font-medium text-zinc-400 mb-2">Components</h3>
            <div className="space-y-1">
              {['RestaurantList.tsx', 'MenuItemList.tsx', 'OrderList.tsx', 'OrderForm.tsx', 'OrderDetail.tsx', 'DeliveryTracker.tsx', 'CartSummary.tsx', 'RestaurantDetail.tsx'].map(f => (
                <div key={f} className="flex items-center gap-2 text-sm bg-zinc-800/50 rounded-lg px-3 py-1.5">
                  <span className="text-blue-400">⚛️</span>
                  <span className="text-zinc-300">{f}</span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <h3 className="text-sm font-medium text-zinc-400 mb-2">Other Files</h3>
            <div className="space-y-1">
              {['database/schema.sql', 'types/index.ts', 'app/layout.tsx', 'app/page.tsx', 'README.md'].map(f => (
                <div key={f} className="flex items-center gap-2 text-sm bg-zinc-800/50 rounded-lg px-3 py-1.5">
                  <span className={f.endsWith('.sql') ? 'text-amber-400' : f.endsWith('.ts') ? 'text-violet-400' : 'text-emerald-400'}>
                    {f.endsWith('.sql') ? '🗃️' : f.endsWith('.ts') ? '📘' : '⚛️'}
                  </span>
                  <span className="text-zinc-300">{f}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
