'use client';

import { useState } from 'react';

export default function LocalReportGenerator() {
  const [report, setReport] = useState({
    title: '',
    author: '',
    department: '',
    period: '',
    color: '#6366f1'
  });

  const [metrics, setMetrics] = useState([
    { name: '', value: '', change: '' }
  ]);

  const [sections, setSections] = useState([
    { title: 'Executive Summary', content: '' }
  ]);

  const [recommendations, setRecommendations] = useState<string[]>([]);
  const [recInput, setRecInput] = useState('');
  const [activeTab, setActiveTab] = useState<'edit' | 'preview'>('edit');

  const addMetric = () => setMetrics([...metrics, { name: '', value: '', change: '' }]);
  const updateMetric = (i: number, field: string, value: string) => setMetrics(metrics.map((m, idx) => idx === i ? { ...m, [field]: value } : m));
  const removeMetric = (i: number) => setMetrics(metrics.filter((_, idx) => idx !== i));

  const addSection = () => setSections([...sections, { title: '', content: '' }]);
  const updateSection = (i: number, field: string, value: string) => setSections(sections.map((s, idx) => idx === i ? { ...s, [field]: value } : s));
  const removeSection = (i: number) => setSections(sections.filter((_, idx) => idx !== i));

  const addRecommendation = () => {
    if (recInput.trim()) {
      setRecommendations([...recommendations, recInput.trim()]);
      setRecInput('');
    }
  };

  const generateReportHtml = (): string => {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${report.title || 'Report'}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', sans-serif; background: #f5f5f5; padding: 40px; }
    .report { max-width: 800px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    .header { border-bottom: 3px solid ${report.color}; padding-bottom: 20px; margin-bottom: 30px; }
    .title { font-size: 28px; font-weight: bold; color: ${report.color}; }
    .meta { color: #666; margin-top: 10px; font-size: 14px; }
    .metrics { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-bottom: 30px; }
    .metric-card { background: #f8f9fa; padding: 20px; border-radius: 12px; text-align: center; }
    .metric-value { font-size: 28px; font-weight: bold; color: ${report.color}; }
    .metric-label { font-size: 13px; color: #666; margin-top: 5px; }
    .metric-change { font-size: 12px; margin-top: 5px; }
    .metric-change.positive { color: #10b981; }
    .metric-change.negative { color: #ef4444; }
    .section { margin-bottom: 25px; }
    .section-title { font-size: 16px; font-weight: 600; color: ${report.color}; border-bottom: 1px solid #eee; padding-bottom: 8px; margin-bottom: 12px; }
    .content { color: #555; line-height: 1.7; font-size: 14px; }
    .recommendations { list-style: none; }
    .recommendations li { padding: 10px; background: #f8f9fa; border-left: 3px solid ${report.color}; margin-bottom: 8px; border-radius: 0 8px 8px 0; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 12px; text-align: center; }
  </style>
</head>
<body>
  <div class="report">
    <div class="header">
      <div class="title">${report.title || 'Report Title'}</div>
      <div class="meta">
        ${report.author ? `<span>By ${report.author}</span>` : ''}
        ${report.department ? `<span> • ${report.department}</span>` : ''}
        ${report.period ? `<span> • ${report.period}</span>` : ''}
      </div>
    </div>

    ${metrics.some(m => m.name) ? `
    <div class="metrics">
      ${metrics.filter(m => m.name).map(m => `
        <div class="metric-card">
          <div class="metric-value">${m.value || '—'}</div>
          <div class="metric-label">${m.name}</div>
          ${m.change ? `<div class="metric-change ${m.change.startsWith('+') ? 'positive' : 'negative'}">${m.change}</div>` : ''}
        </div>
      `).join('')}
    </div>` : ''}

    ${sections.filter(s => s.title || s.content).map(s => `
    <div class="section">
      <div class="section-title">${s.title}</div>
      <div class="content">${s.content.split('\n').map(line => `<p style="margin-bottom:8px">${line}</p>`).join('')}</div>
    </div>`).join('')}

    ${recommendations.length > 0 ? `
    <div class="section">
      <div class="section-title">Recommendations</div>
      <ul class="recommendations">
        ${recommendations.map(r => `<li>${r}</li>`).join('')}
      </ul>
    </div>` : ''}

    <div class="footer">
      Generated by AbhiBase • ${new Date().toLocaleDateString()}
    </div>
  </div>
</body>
</html>`;
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Report Generator</h2>
          <p className="text-zinc-400">Create professional reports instantly - no AI needed</p>
        </div>
        <button onClick={() => setActiveTab(activeTab === 'edit' ? 'preview' : 'edit')} className="px-4 py-2 bg-zinc-700 hover:bg-zinc-600 rounded-lg">
          {activeTab === 'edit' ? '👁️ Preview' : '✏️ Edit'}
        </button>
      </div>

      {activeTab === 'edit' ? (
        <div className="grid lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
              <h3 className="font-semibold mb-4">Report Details</h3>
              <div className="space-y-3">
                <input type="text" value={report.title} onChange={(e) => setReport(prev => ({ ...prev, title: e.target.value }))} placeholder="Report Title" className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2" />
                <div className="grid grid-cols-2 gap-3">
                  <input type="text" value={report.author} onChange={(e) => setReport(prev => ({ ...prev, author: e.target.value }))} placeholder="Author" className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2" />
                  <input type="text" value={report.department} onChange={(e) => setReport(prev => ({ ...prev, department: e.target.value }))} placeholder="Department" className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2" />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <input type="text" value={report.period} onChange={(e) => setReport(prev => ({ ...prev, period: e.target.value }))} placeholder="Period (e.g., Q4 2024)" className="bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2" />
                  <div className="flex gap-2">
                    <input type="color" value={report.color} onChange={(e) => setReport(prev => ({ ...prev, color: e.target.value }))} className="w-10 h-10 rounded" />
                    <input type="text" value={report.color} onChange={(e) => setReport(prev => ({ ...prev, color: e.target.value }))} className="flex-1 bg-zinc-800 border border-zinc-700 rounded px-2 text-sm" />
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">Key Metrics</h3>
                <button onClick={addMetric} className="px-3 py-1 bg-violet-600 hover:bg-violet-700 rounded text-sm">+ Add</button>
              </div>
              <div className="space-y-3">
                {metrics.map((m, i) => (
                  <div key={i} className="grid grid-cols-7 gap-2 items-center">
                    <input type="text" value={m.name} onChange={(e) => updateMetric(i, 'name', e.target.value)} placeholder="Metric" className="col-span-3 bg-zinc-800 border border-zinc-700 rounded px-3 py-2 text-sm" />
                    <input type="text" value={m.value} onChange={(e) => updateMetric(i, 'value', e.target.value)} placeholder="Value" className="col-span-2 bg-zinc-800 border border-zinc-700 rounded px-3 py-2 text-sm" />
                    <input type="text" value={m.change} onChange={(e) => updateMetric(i, 'change', e.target.value)} placeholder="+15%" className="bg-zinc-800 border border-zinc-700 rounded px-3 py-2 text-sm" />
                    <button onClick={() => removeMetric(i)} className="p-2 bg-red-600/20 text-red-400 rounded">✕</button>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="space-y-4">
            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">Report Sections</h3>
                <button onClick={addSection} className="px-3 py-1 bg-violet-600 hover:bg-violet-700 rounded text-sm">+ Add</button>
              </div>
              <div className="space-y-3">
                {sections.map((s, i) => (
                  <div key={i} className="bg-zinc-800/50 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <input type="text" value={s.title} onChange={(e) => updateSection(i, 'title', e.target.value)} className="bg-transparent font-medium" />
                      <button onClick={() => removeSection(i)} className="text-red-400 hover:text-red-300">×</button>
                    </div>
                    <textarea value={s.content} onChange={(e) => updateSection(i, 'content', e.target.value)} placeholder="Section content..." rows={3} className="w-full bg-zinc-800 border border-zinc-700 rounded px-3 py-2 text-sm resize-none" />
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
              <h3 className="font-semibold mb-4">Recommendations</h3>
              <div className="flex gap-2 mb-3">
                <input type="text" value={recInput} onChange={(e) => setRecInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && addRecommendation()} placeholder="Add recommendation..." className="flex-1 bg-zinc-800 border border-zinc-700 rounded px-3 py-2 text-sm" />
                <button onClick={addRecommendation} className="px-3 py-2 bg-violet-600 hover:bg-violet-700 rounded text-sm">+</button>
              </div>
              <ul className="space-y-2">
                {recommendations.map((r, i) => (
                  <li key={i} className="flex items-center justify-between bg-zinc-800/50 rounded px-3 py-2 text-sm">
                    <span>{r}</span>
                    <button onClick={() => setRecommendations(recommendations.filter((_, idx) => idx !== i))} className="text-red-400 hover:text-red-300">×</button>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-6">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-semibold">Preview</h3>
            <div className="flex gap-2">
              <button onClick={() => { const blob = new Blob([generateReportHtml()], { type: 'text/html' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'report.html'; a.click(); }} className="px-3 py-1 bg-violet-600 hover:bg-violet-700 rounded text-sm">💾 Download</button>
            </div>
          </div>
          <iframe srcDoc={generateReportHtml()} className="w-full h-[800px] bg-white rounded-lg" title="Report Preview" />
        </div>
      )}
    </div>
  );
}
