import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Food Delivery App',
  description: 'Generated by AbhiBase AI App Generator',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-950 text-white">
        <nav className="border-b border-zinc-800 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-2xl">🍔</span>
            <span className="font-bold text-lg">Food Delivery</span>
          </div>
          <div className="flex gap-4 text-sm">
            <a href="/" className="text-zinc-400 hover:text-white">Home</a>
            <a href="/orders" className="text-zinc-400 hover:text-white">Orders</a>
            <a href="/cart" className="text-zinc-400 hover:text-white">Cart</a>
          </div>
        </nav>
        <main className="max-w-6xl mx-auto p-6">
          {children}
        </main>
      </body>
    </html>
  )
}
